SuperBlog/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :users

  root "posts#index"

end

SuperBlog/app/models/post.rb
class Post < ActiveRecord::Base

	validates :titulo, :presence => true
	validates :contenido, :presence => true
	validates :user_id, :presence => true


	belongs_to :user
end

SuperBlog/app/models/user.rb
class User < ActiveRecord::Base
	

	has_many :posts
end

SuperBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

SuperBlog/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  respond_to :html ,  :js 


  def index
    @posts=Post.all
  end

  def show

    @post = Post.find(params[:id])

  end

  def new
    
    @post = Post.new

     #al crear el archivo new.js.erb el render que el 
    #controlador hace por defecto lo va a hacer con 
    #formato js porque le puse en el link_to del index.htm
    #el metodo remote: true, es decir hágalo en formato js

  end

  def edit
    @post = Post.find(params[:id])
    #al crear el archivo edit.js.erb el render que el 
    #controlador hace por defecto lo va a hacer con 
    #formato js porque le puse en el link_to del index.htm
    #el metodo remote: true, es decir hágalo en formato js
  end

  def create
    @post = Post.create(post_params)
    #al crear el archivo create.js.erb el render que el 
    #controlador hace por defecto lo va a hacer con 
    #formato js porque le puse en el link_to del index.htm
    #el metodo remote: true, es decir hágalo en formato js
  end

  def update
    @post = Post.update(params[:id], post_params)
    #al crear el archivo update.js.erb el render que el 
    #controlador hace por defecto lo va a hacer con 
    #formato js porque le puse en el link_to del index.htm
    #el metodo remote: true, es decir hágalo en formato js

  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'El post fue destruido exitosamente' }
      format.json { head :no_content }

    end
  end

  private

  def post_params
    params.require(:post).permit(:titulo, :fecha, :publicado, :contenido, :user_id)
  end
end

SuperBlog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all
  end

  def show
    @user= User.find(params[:id])  
  end

  def new
    
    @user = User.new

  end

  def edit

    @user= User.find(params[:id]) 

  end

  def create
    
    @user = User.new(params_user)
    
    respond_to do |format|
      if @user.save
        format.html {redirect_to users_path, notice: 'El autor ha sido creado esxitosamente'}
      else
        format.html {render :new, notice: 'el autor no se ha creado exitosamente, vuelva a intentarlo'}
      end
    end
  end

  def update

     @user= User.find(params[:id]) 

     respond_to do |format|

      if @user.update(params_user)
        format.html {redirect_to @user, notice: 'La información ha sido actualizada esxitosamente'}
      else
        format.html {render :edit, notice: 'la información no se ha actualizado exitosamente, vuelva a intentarlo'}
      end
    end

  end

  def destroy

    @user= User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Se ha eliminado el autor exitosamente.' }
      format.json { head :no_content }
    end
  end

  private

  #params that received from new user form

  def params_user
    params.require(:user).permit(:nombre, :apellido, :email, :empresa)
  end

end

SuperBlog/app/helpers/application_helper.rb
module ApplicationHelper
end

SuperBlog/app/helpers/posts_helper.rb
module PostsHelper
end

SuperBlog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SuperBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


 
  <!-- navbar inicia-->
      <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid" id="navbarCSS">
       <div class="navbar-header" >
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#" id="brand-style" ><strong>Super_</strong><span id="span-block" >Blog</span></a>
       </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="http://www.leaninnovationgroup.com/form/form.html">Contactarlos</a></li>
        </ul> 
        </div>
     </div><!-- /.container-fluid -->
   </nav><!--finaliza el navbar -->

  
 <%=yield %>

 <footer>
        <hr>
        <p style="text-align:center;">Super_Blog|2014 All rights reserved</p>
        
 </footer>

</body>

 
</html>

SuperBlog/app/views/posts/_appendCreate.html.erb
<!-- Es esta vista está el código para hacerle render en 
 el archivo create.js.erb -->

<td><%= @post.titulo %></td>\
<td><%= @post.fecha %>@</td>\
<td><%= @post.publicado %></td>\
<td><%= @post.contenido %></td>\
<td><%= @post.user.nombre%></td>\
<td><%= link_to "mostrar post", @post , class: "btn btn-info" %> </td>\
<td><%= link_to "editar post", edit_post_path(@post), class: "btn btn-default" %></td>\
<td><%= link_to "eliminar post", @post, method: :delete, data: {confrim: "seguro que quieres eliminar este post?"}, class: "btn btn-default"%></td>

SuperBlog/app/views/posts/_create.html.erb
    <h1>Crear un  nuevo  Post</h1>
    <!-- <p>Find me in app/views/posts/create.html.erb</p> -->


  <%= form_for(@post, remote: true) do |f| %>

  <!-- el remote: true le está indicando que el formato que debe renderizar el controlador  es java script para la accion asociada al form -->

  <div>
    <%=f.label :titulo_del_post%> <br>
    <%=f.text_field :titulo %>
  </div>
   <div>
    <%=f.label :Selecciona_el_autor%> <br>
    <%=f.collection_select :user_id, User.all, :id, :nombre, prompt:"selecciona el autor" %>
  </div>
  <div>
    <%=f.label :selecciona_la_fecha_de_creación%> <br>
    <%=f.datetime_select :fecha  %>
  </div>
  <div>
    <%=f.label :escribe_el_contenido_del_post%> <br>
    <%=f.text_area :contenido, size: "40x10" %>
  </div>  

  <div>
    <%= f.label :selecciona_la_casilla_si_quieres_que_aparezca_publicado %>
    <%=f.check_box :publicado%>
  </div>
 
  <div>
  <% if current_page?(:action => 'new') %> 
    <%= f.submit "CREAR EL POST" ,class: "btn btn-success"%>
    <% else %>
    <%= f.submit "MODIFICAR EL POST" ,class: "btn btn-success" %>
    <% end %>

  </div>
  <% end %>

SuperBlog/app/views/posts/_modal.html.erb
   <div class="modal fade" id="new_post_path">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">

                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h4 class="modal-title">Crear un nuevo post</h4>
                </div>
                <div class="modal-body">

                <div id="x" class="alert alert-success" style="display: none">Post creado exitosamente</div>
                <!-- este div se le agrega para que salga el 
                mensaje de post creado exitosamente
                está relacionado a través del id="x" con el archivo
                create.js.erb, el cual se llama con jquery
                con el metodo show, $(#'x').show() -->

                 <div id="update" class="alert alert-success" style="display: none">Post actualizado exitosamente</div>  

                 <!-- este div se le agrega para que salga el 
                mensaje de post actualizado exitosamente
                está relacionado a través del id="update" con el archivo
                update.js.erb, el cual se llama con jquery
                con el metodo show, $(#'update').show() -->
                
                  
                <%= render 'create' %>
                  
                </div>
               </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
    </div><!-- /.ends modal new_post_path -->

SuperBlog/app/views/posts/create.js.erb
/* este es el archivo que el controlador va a tomar como acción de create.
Para que lo tome toca modificar el rdirect_to  */

<% if @post.errors.any? %>
	alert('Verifique campos requeridos')
	<% @post.errors.full_messages.each do |msg| %>
	  alert('<%= msg %>');
	<% end %>
<% else %>

	$('#x').show();

	$('#idParaAppend').append('<tr><%=j render "appendCreate"%></tr>');
        
<%end%>

SuperBlog/app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

SuperBlog/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'create' %>

<%= link_to 'mostrar post', @post %> |
<%= link_to 'ver todos los posta', posts_path %>

SuperBlog/app/views/posts/edit.js.erb
/* working with java script in rails. 
Aquí estamos llamando el metodo de modal de  bootstrap: 
http://getbootstrap.com/javascript/#modals  esto via Java Script  */

$("<%= j render 'modal'%>").modal();

/* la j hace referencia a escape_javascript para que
pueda renderizar un archivo que viene en diferentes líneas
modal es el nombre del archivo _modal.htm.erb al que le voy a hacer render 
.modal() es el método para mostral el modal , viene en la gem de bootstrap*/

SuperBlog/app/views/posts/index.html.erb
<% if notice != nil  %>
  <p id="notice" class="alert alert-success" ><%= notice %></p>
<% end %>


<div class="container">
  

<h1>Todos los posts</h1>
<div>
  <td><%= link_to 'crear un nuevo post', new_post_path, remote: true, style:"float:right", class: "btn btn-success"%></td>
  <!-- el remote: true le está indicando que el formato que debe renderizar el controlador es java script-->
</div>

<table class="table table-condensed">
	<thead>

		<tr>
			<th>TITULO</th>
      <th>FECHA</th>
      <th>PUBLICADO</th>
      <th>CONTENIDO</th>
      <th>AUTOR</th>
      
		</tr>	
	</thead>
  <tbody id= "idParaAppend">
    <% @posts.each do |post| %>
      <tr id = <%= post.id %>>
        <td><%= post.titulo %></td>
        <td><%= post.fecha %></td>
        <td><%= post.publicado %></td>
        <td><%= post.contenido %></td>
        <td><%= post.user.nombre%></td>
        <td><%= link_to 'mostrar post', post,  class: "btn btn-info"%> </td>
        <td><%= link_to 'editar post', edit_post_path(post), remote: true, class: "btn btn-default" %></td>
        <td><%= link_to 'eliminar post', post, method: :delete, data: {confrim: 'seguro que quieres eliminar este post?'},class: "btn btn-default" %></td>
      </tr>
    <% end -%>
  </tbody>

</table>
</div>

SuperBlog/app/views/posts/new.html.erb
<!-- este archivo se podría borrar porque ya el controlador
no está enrutando con respond_to hacía post/new sino que
va a tomar el archivo new.js.erb porque al form se le puso el 
método remote: true -->

<h1>New post</h1>

<%= render 'create' %>
<!-- esta linea rederiza el _create.html.erb en el que está el form-->
<br>

<%= link_to 'Back', posts_path%>

SuperBlog/app/views/posts/new.js.erb
/* working with java script in rails. 
Aquí estamos llamando el metodo de modal de  bootstrap: 
http://getbootstrap.com/javascript/#modals  esto via Java Script  */

$("<%= j render 'modal'%>").modal();

/* la j hace referencia a escape_javascript para que
pueda renderizar un archivo que viene en diferentes líneas
modal es el nombre del archivo _modal.htm.erb al que le voy a hacer render 
.modal() es el método para mostral el modal , viene en la gem de bootstrap*/

SuperBlog/app/views/posts/show.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>template_posts</title>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href="style.css">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
        <style>
           p {font-size: 18px;

            margin-bottom: 30px;
            margin-top: 30px;}
        </style>
    
    </head> 
    <!-- notificacion de mensajes inicia -->
    <p id="notice"><%= notice %></p>

    <!-- notificacion de mensajes termina -->
    

  <!--inicia titulo deberá revisar el post -->

    <div class="container" style="line-height:1.8;">
        <div class="row">
            <div class="col-md-7" >
                <h2><%= @post.titulo %></h2> <!--titulo -->
                <h4>consultas de este recurso| 2300</h4><!--consultas-->
                <h3><%= @post.fecha%> <h3><!--fecha -->
                <hr>
                <hr>
                <p>
                  <strong>Sabias que ...</strong>
                    <%= @post.contenido%><!--contenido -->
                </p>
            </div>
          <div class="col-md-1"></div>
          <div class="col-md-4" >
                <h4>VIA <spam><%= @post.user.email%></spam>   </h4>
                <hr>
                <img style="border-radius:50%; position:float-left; margin-left: 1px;
                margin-bottom: 20px;"src="http://lorempixel.com/150/150/people/" alt=""><p style="font-size:13px; color: #7f8c8d;"><em>
                <!-- bio autor -->  
                </em></p>
                <p>
                  <strong>Fecha:</strong>
                  <%= @post.fecha%>
                </p>

          </div>
        
        </div> 
        
        <%= link_to 'ver todos los posts', posts_path, class: "btn btn-info"%> 
    </div>


    <div class="container-fluid" style="line-height:1.8;">
        <div class="row">
            <div class="col-md-2" > </div>
            <div class="col-md-8" style="text-align:center;">
                <h4>quieres saber más de nosotros?</h4>
                    <button style= "margin-bottom:20px; margin-top:20px;"type="button" id="firstbutton" class="btn btn-success" btn-group-justified>
                        <a target="_blank" style="color:white; margin-bottom:20px;" href="#">conoce Super_Blog</a>
                    </button>
            </div>
            <div class="col-md-2" > </div>

        </div>
    </div>

   
</html>

SuperBlog/app/views/posts/update.html.erb
<!-- este archivo se podría borrar porque ya el controlador
no está enrutando con respond_to hacía post/new sino que
va a tomar el archivo new.js.erb porque al form se le puso el 
método remote: true -->

<!-- <h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p> -->

SuperBlog/app/views/posts/update.js.erb
/* este es el archivo que el controlador va a tomar como acción de create.
Para que lo tome toca modificar el rdirect_to  */

<% if @post.errors.any? %>
	alert('Verifique campos requeridos')
	<% @post.errors.full_messages.each do |msg| %>
	  alert('<%= msg %>');
	<% end %>
<% else %>

	

	$('#<%= @post.id %>').html('<%=j render "appendCreate"%>');

	$('#update').show();
        
<%end%>

SuperBlog/app/views/users/_create.html.erb
    <h1>Crear un nuevo Autor</h1>
    <!-- <p>Find me in app/views/posts/create.html.erb</p> -->
  <%= form_for @user do |f| %>

  <div>
    <%=f.label :Nombre_del_autor%> <br>
    <%=f.text_field :nombre %>
  </div>
  <div>
    <%=f.label :Apellido_del_autor%> <br>
    <%=f.text_field :apellido %>
  </div>
   <div>
    <%=f.label :email_del_autor%> <br>
    <%=f.text_field :email%>
  </div>
   <div>
    <%=f.label :empresa_en_la_que_trabaja_el_autor%> <br>
    <%=f.text_field :empresa%>
  </div>
    <div class="actions" > 

    <% if current_page?(:action => 'new') %>
    
    <%= f.submit "CREAR NUEVO AUTOR", class: ""%>
    <%else%>
    <%= f.submit "MODIFICAR NUEVO AUTOR", class: ""%>
    <% end %>
  </div>
  <% end %>

SuperBlog/app/views/users/destroy.html.erb
<p id="notice"><%= notice %></p>

SuperBlog/app/views/users/edit.html.erb
<p id="notice"><%= notice %></p>
<h1>Editar Autor</h1>

<%= render 'create' %>

<%= link_to 'Mostrar autor', @user %>
<%= link_to 'Ver todos los autores', users_path %>

SuperBlog/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Todos los Autores</h1>
<%= link_to 'crear un nuevo user', new_user_path%>
<table>
	<thead>

		<tr>
			<th>NOMBRE</th>
      <th>APELLIDO</th>
      <th>EMAIL</th>
      <th>EMPRESA</th>
      <th>MOSTRAR AUTOR</th>
      <th>EDITAR AUTOR</th>
      <th>ELIMINAR AUTOR</th>
      
		</tr>	
	</thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nombre %></td>
        <td><%= user.apellido %></td>
        <td><%= user.email %></td>
        <td><%= user.empresa %></td>
        <td><%= link_to 'mostrar user', user %></td>
        <td><%= link_to 'editar user', edit_user_path(user) %></td>
        <td><%= link_to 'eliminar user', user, method: :delete, data: {confrim: 'seguro que quieres eliminar este autor?'}%></td>
      </tr>
    <% end -%>
  </tbody>


</table>

SuperBlog/app/views/users/new.html.erb
<!--<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p> -->
<p id="notice"><%= notice %></p>
<h1>Nuevo Autor</h1>

<%= render 'create' %>
<br>

<%= link_to 'volver al listado de autores actuales', users_path%>
<%= link_to 'ver los post', posts_path%>

SuperBlog/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @user.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @user.apellido %>
</p>

<p>
  <strong>email:</strong>
  <%= @user.email%>
</p>

<p>
  <strong>empresa:</strong>
  <%= @user.empresa%>
</p>

<%= link_to 'Editar autor', edit_user_path(@user) %> |
<%= link_to 'ver todos los autores', users_path %>